// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQ8ZIA6yu09Ofg0uul_UsseOnDXSbyuQ',
    appId: '1:985333086710:web:bc20c094f12ed239ed6fd7',
    messagingSenderId: '985333086710',
    projectId: 'second-app-85b7e',
    authDomain: 'second-app-85b7e.firebaseapp.com',
    storageBucket: 'second-app-85b7e.firebasestorage.app',
    measurementId: 'G-TYB77EGZ8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBxf3k74DQ0Q4AmO1NkaC8xC60LzwHmc',
    appId: '1:985333086710:android:641d4ceedd50b51fed6fd7',
    messagingSenderId: '985333086710',
    projectId: 'second-app-85b7e',
    storageBucket: 'second-app-85b7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMZIlUulSx8aRPqO29lLSATWxz5gwJh4',
    appId: '1:985333086710:ios:5318eacaf977ecbded6fd7',
    messagingSenderId: '985333086710',
    projectId: 'second-app-85b7e',
    storageBucket: 'second-app-85b7e.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWMZIlUulSx8aRPqO29lLSATWxz5gwJh4',
    appId: '1:985333086710:ios:5318eacaf977ecbded6fd7',
    messagingSenderId: '985333086710',
    projectId: 'second-app-85b7e',
    storageBucket: 'second-app-85b7e.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxQ8ZIA6yu09Ofg0uul_UsseOnDXSbyuQ',
    appId: '1:985333086710:web:df4d88394d03f5c9ed6fd7',
    messagingSenderId: '985333086710',
    projectId: 'second-app-85b7e',
    authDomain: 'second-app-85b7e.firebaseapp.com',
    storageBucket: 'second-app-85b7e.firebasestorage.app',
    measurementId: 'G-6ZXPMRVKMY',
  );

}